--------------------------------------------------------------
-- Creating an aggregated view for weekly shopping
--includes visits and sales at the weekly level
--------------------------------------------------------------
DROP VIEW RFM
CREATE VIEW RFM AS 
SELECT 
R.[H_KEY]
,[AGE_DESC]
,[MARITAL_STATUS_CODE]
,[INCOME_DESC]
,[HOMEOWNER_DESC]
,[HH_COMP_DESC]
,[HOUSEHOLD_SIZE_DESC]
,[KID_CATEGORY_DESC]

,[FAMILY_TOT_SALES] AS ANNUAL_SALES
,[FAMILY_TOT_VISITS] AS ANNUAL_VISITS
,[FAMILY_VALUE] AS ANNUAL_BASKET_VALUE

,RECENCY
,FREQUENCY
,MONETARY
FROM
		(
		SELECT
		REC.H_KEY,
		REC.RECENCY,
		CASE WHEN FREQ_MON.FREQUENCY IS NULL THEN 0 ELSE FREQ_MON.FREQUENCY END AS FREQUENCY,
		CASE WHEN FREQ_MON.MONETARY IS NULL THEN 0 ELSE FREQ_MON.MONETARY END AS MONETARY
		FROM
			(
			SELECT
			H_KEY,
			MAX([DAY]) AS LATEST_SHOP,
			365 - MAX([DAY])+1 AS RECENCY
			FROM SUPERMARKET_FILTER_VIEW VW
			GROUP BY H_KEY
			)REC
			LEFT JOIN 
			(
			SELECT
			H_KEY,
			COUNT(DISTINCT [BASKET_ID]) AS FREQUENCY,
			SUM([TRANS_VALUE]) AS MONETARY
			FROM SUPERMARKET_FILTER_VIEW VW
			WHERE [DAY] BETWEEN 365-4*7 AND 365 --1 MONTH
			GROUP BY H_KEY
			)FREQ_MON
			ON REC.H_KEY = FREQ_MON.H_KEY
		)R
INNER JOIN 
		(
		SELECT 
		[H_KEY]
		,[AGE_DESC]
		,[MARITAL_STATUS_CODE]
		,[INCOME_DESC]
		,[HOMEOWNER_DESC]
		,[HH_COMP_DESC]
		,[HOUSEHOLD_SIZE_DESC]
		,[KID_CATEGORY_DESC]
		,[FAMILY_TOT_SALES]
		,[FAMILY_TOT_VISITS]
		,[FAMILY_VALUE]
		FROM [SUPERMARKET].[dbo].[SUPERMARKET_FILTER_VIEW] F_VW
		WHERE [PRODUCT_ID] in (
								SELECT [PRODUCT_ID]
								FROM [SUPERMARKET].[dbo].[SUPERMARKET_FILTER_VIEW]
								group by [PRODUCT_ID]
								HAVING COUNT(DISTINCT [H_KEY]) >=25
								)
					GROUP BY   
					[H_KEY]
					,[AGE_DESC]
					,[MARITAL_STATUS_CODE]
					,[INCOME_DESC]
					,[HOMEOWNER_DESC]
					,[HH_COMP_DESC]
					,[HOUSEHOLD_SIZE_DESC]
					,[KID_CATEGORY_DESC]
					,[FAMILY_TOT_SALES]
					,[FAMILY_TOT_VISITS]
					,[FAMILY_VALUE]
		)
		F_VW
		ON R.H_KEY = F_VW.H_KEY
